// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAlert: typeof import('./src/components/TheAlert.vue')['default']
    TheAvatar: typeof import('./src/components/TheAvatar.vue')['default']
    TheBadge: typeof import('./src/components/TheBadge.vue')['default']
    TheBalancer: typeof import('./src/components/TheBalancer.vue')['default']
    TheButton: typeof import('./src/components/TheButton.vue')['default']
    TheChip: typeof import('./src/components/TheChip.vue')['default']
  }
}
